import { Inter,Roboto,Lato,Moon_Dance } from "next/font/google";
import "./globals.css";
import LoadingIndicator from "@/components/LoadingIndicator";

const inter = Inter ({
  subsets : ['latin'],
  display : 'swap'
  
})
const roboto = Roboto ({
  subsets : ['latin'],
  display : 'swap',
  weight : ['400']
  
})
const lato = Lato ({
  subsets : ['latin'],
  display : 'swap',
  weight : ['400']
  
})
const moon_dance = Moon_Dance ({
  subsets : ['latin'],
  display : 'swap',
  weight : ['400']
  
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={lato.className}
      >
        <LoadingIndicator />
        {children}
      </body>
    </html>
  );
}
